import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "한국임상정보",
  description: "Generated by create next app",
  icons: {
    icon: "logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
